[package]
name = "ros_package_manifest"
version = "0.1.0"
authors = ["Gérald Lelong <gerald.lelong@easymov.fr>"]
edition = "2018"

[dependencies]
regex = "1.2.0"
once_cell = "0.2.4"
roxmltree = "0.6.1"
err-derive = "0.1.5"